# Generated by Django 4.2.4 on 2023-08-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('esperando aprovação', 'Esperando aprovação'), ('ativado', 'Ativado'), ('deletado', 'Deletado')], default='ativado', max_length=50),
        ),
    ]
