# Generated by Django 4.2.4 on 2023-08-21 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0009_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='user',
            new_name='order',
        ),
    ]
