# Generated by Django 4.2.4 on 2023-08-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0012_alter_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='esta_pago',
        ),
        migrations.AddField(
            model_name='order',
            name='pagamento_intent',
            field=models.BooleanField(default=False),
        ),
    ]
