# Generated by Django 4.2.4 on 2023-08-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0013_remove_order_esta_pago_order_pagamento_intent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='merc_id',
        ),
        migrations.AddField(
            model_name='order',
            name='esta_pago',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='pagamento_intent',
            field=models.CharField(max_length=255),
        ),
    ]
