# Generated by Django 4.2.4 on 2023-08-21 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0015_rename_pagamento_intent_order_payment_intent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_max',
            field=models.IntegerField(),
        ),
    ]
